In [36]:
from helpers_given import *
from preprocess import *
from helpers import *

Load data with helpers_given

In [3]:
x_train, x_test, y_train, train_ids, test_ids = load_csv_data("dataset/", sub_sample=False)

y_train loaded
x_train loaded
x_test loaded


In [4]:
nb_col = x_train.shape[1]
nb_rows = x_train.shape[0]
print(nb_col)
print(nb_rows)

321
328135


In [5]:
y_01 = convert_minus1_to_0(y_train)

In [6]:
print(y_01)
print(y_01[y_01==0].shape)
print(y_01[y_01==1].shape)

[0. 0. 0. ... 0. 0. 0.]
(299160,)
(28975,)


In [7]:
with open('dataset/x_train.csv', 'r') as f:
    features_string = f.readline()
    features = features_string.split(',')
features = features[1:]

Preprocessing of run.py

In [8]:
nb_nans = np.zeros(nb_col)
for i, col in enumerate(x_train.T):
    nb_nans[i] = np.count_nonzero(np.isnan(col))

In [9]:
#nb_nans = number_of_NaNs(features, x_train)
reduced_data, reduced_features, Removed_features = removing_features(nb_nans, features, x_train)
#need to apply the same transfo to x_test
reduced_test = np.delete(x_test, Removed_features, 1)

In [10]:
# Get feature correlation dictionary
feature_correlation_dict = create_dictionary_from_correlation(reduced_data,reduced_features,0.6)

max_corrr_feature_dict = {}

# Find the 50 most correlated features
for key, val in feature_correlation_dict.items():
    max_corrr_feature_dict[key] = len(val)

 Finished for feature: _STATE
 Finished for feature: FMONTH
 Finished for feature: IDATE
 Finished for feature: IMONTH
 Finished for feature: IDAY
 Finished for feature: IYEAR
 Finished for feature: DISPCODE
 Finished for feature: SEQNO
 Finished for feature: _PSU
 Finished for feature: GENHLTH
 Finished for feature: PHYSHLTH
 Finished for feature: MENTHLTH
 Finished for feature: HLTHPLN1
 Finished for feature: PERSDOC2
 Finished for feature: MEDCOST
 Finished for feature: CHECKUP1
 Finished for feature: BPHIGH4
 Finished for feature: BLOODCHO
 Finished for feature: CVDSTRK3
 Finished for feature: ASTHMA3
 Finished for feature: CHCSCNCR
 Finished for feature: CHCOCNCR
 Finished for feature: CHCCOPD1
 Finished for feature: HAVARTH3
 Finished for feature: ADDEPEV2
 Finished for feature: CHCKIDNY
 Finished for feature: DIABETE3
 Finished for feature: SEX
 Finished for feature: MARITAL
 Finished for feature: EDUCA
 Finished for feature: RENTHOM1
 Finished for feature: VETERAN3
 Finished fo

In [11]:
# Sort the dictionary by value in descending order
max_corrr_feature_dict = {k: v for k, v in sorted(max_corrr_feature_dict.items(), key=lambda item: item[1], reverse=True)}

features_to_drop = []
for key in max_corrr_feature_dict.keys():
    features_to_drop.append(key)
    if len(features_to_drop) == 30:
        break

# Define features to keep
features_to_keep = []
for feature in reduced_features:
    if feature not in features_to_drop:
        features_to_keep.append(feature)

# Also replace some features with their calculated counterparts
origin_calculated_features = {
    'WEIGHT2' : 'WTKG3',
    'HEIGHT3' : 'HTM4',
    'ALCDAY5' : '_DRNKWEK',
    'FRUITJU1' : 'FTJUDA1_',
    'FRUIT1' : 'FRUTDA1_',
    'FVBEANS' : 'BEANDAY_',
    'FVGREEN' : 'GRENDAY_',
    'FVORANG' : 'ORNGDAY_',
    'VEGETAB1' : 'VEGEDA1_',
    'STRENGTH' : 'STRFREQ_'
}

# In features_to_keep replace the key of origin_calculated_features with the value
for key, val in origin_calculated_features.items():
    for i, feature in enumerate(features_to_keep):
        if key == feature:
            features_to_keep[i] = val

# Drop duplicates
features_to_keep = list(set(features_to_keep))

# Get the indices of the selected features
selected_features_indices = []
for feature in features_to_keep:
    selected_features_indices.append(reduced_features.index(feature))

selected_features_indices = sorted(selected_features_indices)

# Create a new dataset with keeping the features that are in the selected_features_indices
reduced_data = reduced_data[:,selected_features_indices]
reduced_test = reduced_test[:,selected_features_indices]

# Also remove the features from the reduced_features list
reduced_features_2 = []
for feature in reduced_features:
    if feature in features_to_keep:
        reduced_features_2.append(feature)

# Remove redundant features
redundant_features = [ 'FMONTH','IDATE','IMONTH','IDAY','IYEAR', 'SEQNO', '_STATE', '_PSU', ]
# Get the indices of these features
redundant_features_indices = []
for feature in redundant_features:
    redundant_features_indices.append(reduced_features_2.index(feature))

# Create a new dataset with removing the features that are in the selected_features_indices
reduced_data = np.delete(reduced_data, redundant_features_indices, 1)
reduced_features_2 = [reduced_features_2[i] for i in range(len(reduced_features_2)) if i not in redundant_features_indices]
reduced_test = np.delete(reduced_test, redundant_features_indices, 1)

# Replace nine values with NaNs
replace_nine_with_nan(reduced_data)
replace_nine_with_nan(reduced_test)

# Replace seven values with NaNs
replace_seven_with_nan(reduced_data)
replace_seven_with_nan(reduced_test)

# Replace 99 values with NaNs
replace_99_with_nan(reduced_data)
replace_99_with_nan(reduced_test)

# For the _DRNKWEK feature, replace 9990 with NaN
for i in range(reduced_data.shape[0]):
    if reduced_data[i, reduced_features_2.index('_DRNKWEK')] == 9990:
        reduced_data[i, reduced_features_2.index('_DRNKWEK')] = np.nan
for i in range(reduced_test.shape[0]):
    if reduced_test[i, reduced_features_2.index('_DRNKWEK')] == 9990:
        reduced_test[i, reduced_features_2.index('_DRNKWEK')] = np.nan



In [12]:
# Remove outliers
reduced_data = clean_outliers_modified(reduced_data)
reduced_test = clean_outliers_modified(reduced_test)

# Replace NaNs with medians
reduced_mean = replace_NaN(reduced_data, method='mean')
reduced_mean_test = replace_NaN(reduced_test, method='mean')

# Standardize the data
standardized_x = standardize_data(reduced_mean)
standardized_test = standardize_data(reduced_mean_test)

In [13]:
# Replace NaNs with medians
reduced_median = replace_NaN(reduced_data, method='median')
reduced_median_test = replace_NaN(reduced_test, method='median')

# Standardize the data
std_x_med = standardize_data(reduced_mean)
std_test_med = standardize_data(reduced_mean_test)

#### Run the methods

In [39]:
from implementations import *
NB_COL = standardized_x.shape[1] # corresponds to 'D' = number of features
NB_ROWS = standardized_x.shape[0] # corresponds to 'N' = number of observations/respondents

In [62]:
print(NB_COL)
print(NB_ROWS)

92
328135


In [ ]:
# CV on two hyperparams degree and lambda on regularized logistic regression adding polynomial functi
seed = 12
degrees = np.arange(0,5,1)
k_fold = 4
lambdas = np.arange(0.1,0.5,0.1)
gamma = 0.5
max_iters = 50
initial_w = np.zeros(NB_COL)
k_indices = build_k_indices(y_01, k_fold, seed)
#for each degree, we compute the best lambdas and the associated rmse
best_lambdas = []
best_F1s = []
#vary degree
for degree in degrees:
    # cross validation
    F1_te = []
    for lambda_ in lambdas:
        F1_te_tmp = []
        for k in range(k_fold):
            _, F1_test = cross_validation(y_01, standardized_x,initial_w, max_iters, gamma, k_indices, k, lambda_, degree)
            F1_te_tmp.append(F1_test)
        F1_te.append(np.mean(F1_te_tmp))
    print(f" Finished for degree: {degree}")
    ind_lambda_opt = np.argmax(F1_te)
    best_lambdas.append(lambdas[ind_lambda_opt])
    best_F1s.append(F1_te[ind_lambda_opt])
ind_best =  np.argmax(best_F1s)      
best_degree = degrees[ind_best]
best_lambda = best_lambdas[ind_best]
best_F1 = best_F1s[ind_best]

 Finished for degree: 0
 Finished for degree: 1
 Finished for degree: 2


In [16]:
# GD
w_mse_gd, loss_mse_gd = mean_squared_error_gd(y_01, standardized_x, initial_w = np.zeros(NB_COL), max_iters = 50, gamma = 0.001)
print(loss_mse_gd)
y_mse_gd = standardized_x @ w_mse_gd
y_mse_gd = convert_predict(y_mse_gd)
y_mse_gd = convert_0_to_minus1(y_mse_gd)
print(y_mse_gd)

0.041184898773991556
[-1.  1. -1. ...  1. -1. -1.]


In [17]:
# check the error by comparing y_train and the prediction with x_train
p_gd = (np.sum(y_train!=y_mse_gd)/NB_ROWS)*100 #percentage of false predictions
print(p_gd)

37.16915294010087


In [18]:
# Least squares
w_ls, loss_ls = least_squares(y_01, standardized_x)
print(loss_ls)
y_ls = convert_0_to_minus1(convert_predict(standardized_x @ w_ls))
print(y_ls)

0.03804700436767956
[-1.  1. -1. ... -1. -1. -1.]


plutot genant et bien bien BIIIIEn casse couilles

In [19]:
# accuracy
p_ls = (np.sum(y_train!=y_ls)/NB_ROWS)*100 #percentage of false predictions
print(p_ls)

33.33414600697884


In [22]:
# Ridge regression
w_rr, loss_rr = ridge_regression(y_01, standardized_x, lambda_ = 0.5)
print(loss_rr)
y_rr = convert_0_to_minus1(convert_predict(standardized_x @ w_rr))
print(y_rr)

0.038122678610144185
[-1.  1. -1. ...  1. -1. -1.]


In [25]:
# accuracy
p_rr = (np.sum(y_train!=y_rr)/NB_ROWS)*100 #percentage of false predictions
print(p_rr)

35.47655690493242


In [33]:
# logistic regression (GD)
w_lrgd, loss_lrgd = logistic_regression(y_01, standardized_x, initial_w = np.zeros(NB_COL), max_iters = 50, gamma = 0.2)
print(loss_lrgd)
y_lrgd = convert_0_to_minus1(convert_predict(standardized_x @ w_lrgd))
#y_lrgd = convert_0_to_minus1(y_sigmoid)
print(y_lrgd)
#log sgd
#w_lrsgd, loss_lrsgd = logistic_regression_SGD(y_train, x_train, initial_w = np.zeros(NB_COL), max_iters = 50, gamma = 0.1, lambda_ = 0.5)

0.6663071026110229
[-1.  1. -1. ... -1. -1. -1.]


In [34]:
# accuracy
p_lrgd = (np.sum(y_train!=y_lrgd)/NB_ROWS)*100 #percentage of false predictions
print(p_lrgd)

33.5822146372682


In [86]:
w_reg, loss_reg = reg_logistic_regression(y_01, standardized_x, initial_w = np.zeros(NB_COL), max_iters = 50, gamma = 0.2, lambda_ = 0.0001)
print(loss_reg)
y_reg = convert_0_to_minus1(convert_predict(standardized_x @ w_reg))
print(y_reg)
# reg log sgd
#w_reg_lrsgd, loss_reg_lrsgd = reg_logistic_regression_SGD(y_train, x_train, initial_w = np.zeros(NB_COL), max_iters = 50, gamma = 0.1, lambda_ = 0.5)

0.6663080338133123
[-1.  1. -1. ... -1. -1. -1.]


In [49]:
# accuracy
p_reg = (np.sum(y_train!=y_reg)/NB_ROWS)*100 #percentage of false predictions
print(p_reg)

33.58617642129002


### Create a csv file with a prediction

In [87]:
# predict y with x_test using regularized log
y_pred = convert_0_to_minus1(convert_predict(standardized_test @ w_reg))
print(y_pred)

[ 1. -1.  1. ... -1.  1. -1.]


In [88]:
create_csv_submission(test_ids, y_pred, "submission")

### OLD VERSION:

Take care of the NaNs

In [ ]:
nb_nans = np.zeros(nb_col)
for i, col in enumerate(x_train.T):
    nb_nans[i] = np.count_nonzero(np.isnan(col))
plt.figure(figsize=(10, 5))
plt.hist(nb_nans, bins=20)
plt.title("Number of NaNs per feature before")


In [ ]:
reduced_x_train, reduced_ids = removing_features(nb_nans, train_ids, x_train)

for i, col in enumerate(reduced_x_train.T):
    nb_nans[i] = np.count_nonzero(np.isnan(col))
plt.figure(figsize=(10, 5))
plt.hist(nb_nans, bins=20)
plt.title("Number of NaNs per feature after")

Standardize and remove nans

In [ ]:
# remove the columns that have the same value in it (avoid std=0)
reduced_x_train, reduced_ids = remove_identic_col(reduced_ids, reduced_x_train)
nb_col_reduced = reduced_x_train.shape[1]
print(nb_col_reduced)

In [ ]:
x_standardized = standardize_data(reduced_x_train)

clean_x_train = replace_NaN(x_standardized, method = 'mean')

## Run the methods a first time to see how we're doing

In [ ]:
from implementations import *
NB_COL = clean_x_train.shape[1] # corresponds to 'D' = number of features
NB_ROWS = clean_x_train.shape[0] # corresponds to 'N' = number of observations/respondents

### Gradient descent

In [ ]:
w_mse_gd, loss_mse_gd = mean_squared_error_gd(y_train, clean_x_train, initial_w = np.zeros(NB_COL), max_iters = 50, gamma = 0.001)
print(loss_mse_gd)
y_mse_gd = clean_x_train @ w_mse_gd
y_mse_gd = convert_predict(y_mse_gd)
print(y_mse_gd)

In [ ]:
print(y_train)

### Subgradient descent

In [ ]:
w_mse_sgd, loss_mse_sgd = mean_squared_error_sgd(y_train, clean_x_train, initial_w = np.zeros(NB_COL), max_iters = 50, gamma = 0.001)
print(loss_mse_gd)
y_mse_gd = clean_x_train @ w_mse_gd
y_mse_gd = convert_predict(y_mse_gd)
print(y_mse_gd)

In [ ]:
w_ls, loss_ls = least_squares(y_train, x_train)
w_rr, loss_rr = ridge_regression(y_train, x_train, lambda_ = 0.5)
w_lrgd, loss_lrgd = logistic_regression(y_train, x_train, initial_w = np.zeros(NB_COL), max_iters = 50, gamma = 0.1, lambda_ = 0.5)
w_lrsgd, loss_lrsgd = logistic_regression_SGD(y_train, x_train, initial_w = np.zeros(NB_COL), max_iters = 50, gamma = 0.1, lambda_ = 0.5)
w_reg_lrgd, loss_reg_lrgd = reg_logistic_regression(y_train, x_train, initial_w = np.zeros(NB_COL), max_iters = 50, gamma = 0.1, lambda_ = 0.5)
w_reg_lrsgd, loss_reg_lrsgd = reg_logistic_regression_SGD(y_train, x_train, initial_w = np.zeros(NB_COL), max_iters = 50, gamma = 0.1, lambda_ = 0.5)

Idea to remove columns: compare means in population y=0 and y=1, and remove col for which those means are close
(this is done already a little with remove_identic_col for the columns that have the same value in each cell)

Cleaning outliers

In [ ]:
removed_outlier_x_train = clean_outliers(reduced_x_train)

In [ ]:
features_below_10_unique_values = {}
for i in range(reduced_x_train.shape[1]):
    # print(f"{reduced_features[i]}: {len(np.unique(reduced_data[:,i]))}")
    #print(f"{reduced_features[i]}: {np.unique(reduced_x_train[:,i])}")
    if len(np.unique(reduced_x_train[:,i])) < 10:
        features_below_10_unique_values[reduced_features[i]] = len(np.unique(reduced_x_train[:,i]))

# dealing with correlation 

def create_dictionary_from_correlation(correlation_threshold):
    newfeature_correlation_dict = {}
    # For each feature in the dataset calculate the correlation with the others and save those which have higher than 0.6 correlation
    for ft_num, feature in enumerate(reduced_features):
        newfeature_correlation_dict[feature] = []
        for o_ft_num, other_feature in enumerate(reduced_features):
            if (feature != other_feature):
                if np.abs(np.corrcoef(reduced_x_train[:,ft_num],reduced_x_train[:,o_ft_num])[0,1]) >= correlation_threshold:
                    newfeature_correlation_dict[feature].append(other_feature)
        print(f" Finished for feature: {feature}")
    return newfeature_correlation_dict

feature_correlation_dict = create_dictionary_from_correlation(0.6)
with open('feature_correlation_dict.pickle', 'wb') as handle:
    pickle.dump(feature_correlation_dict, handle, protocol=pickle.HIGHEST_PROTOCOL)
with open('feature_correlation_dict.pickle', 'rb') as handle:
    feature_correlation_dict = pickle.load(handle)

### Run the functions on the data

In [ ]:
from implementations import *
w_mse_gd, loss_mse_gd = mean_squared_error_gd(y_train, x_train, initial_w = np.array([0,0]), max_iters = 50, gamma = 0.1)
w_mse_sgd, loss_mse_sgd = mean_squared_error_sgd(y_train, x_train, initial_w = np.array([0,0]), max_iters = 50, gamma = 0.1)
w_ls, loss_ls = least_squares(y_train, x_train)
w_rr, loss_rr = ridge_regression(y_train, x_train, lambda_ = 0.5)
w_lrgd, loss_lrgd = logistic_regression_GD(y_train, x_train, initial_w = np.array([0,0]), max_iters = 50, gamma = 0.1, lambda_ = 0.5)
w_lrsgd, loss_lrsgd = logistic_regression_SGD(y_train, x_train, initial_w = np.array([0,0]), max_iters = 50, gamma = 0.1, lambda_ = 0.5)
w_reg_lrgd, loss_reg_lrgd = regularized_logistic_regression_GD(y_train, x_train, initial_w = np.array([0,0]), max_iters = 50, gamma = 0.1, lambda_ = 0.5)
w_reg_lrsgd, loss_reg_lrsgd = regularized_logistic_regression_SGD(y_train, x_train, initial_w = np.array([0,0]), max_iters = 50, gamma = 0.1, lambda_ = 0.5)